### ISSUE TITLE
Can not download PG driver from maven central

### ISSUE THREAD

**Issue by pendula95** [mortenterhart/heroku-buildpack-wildfly-postgresql#2]
Since 15 of January the maven central urls have changed and HTTP is not supported anymore. [More info](https://support.sonatype.com/hc/en-us/articles/360041287334-Central-501-HTTPS-Required)
Buildpack will fail as it is not able to download PG driver.
Cause:
https://github.com/mortenterhart/heroku-buildpack-wildfly-postgresql/blob/dfc60f63f2ac7a440123e7425667dc6dd29aa293/lib/postgresql_driver.sh#L329

**Comment by mortenterhart** [comment]
Hey, thanks for the useful hint. I didn't notice the change in the Maven URLs and I could reproduce the issue with one of my applications. I tested your fix and the PG driver is downloaded without failure there, so I will approve your PR.
